name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: :99
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4.7.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Run tests on Linux
      if: matrix.os == 'ubuntu-latest'
      uses: nick-invision/retry@v3.0.2
      with:
        timeout_minutes: 30
        max_attempts: 1
        command: |
          mvn -B test -Dtest=Docker*
          Xvfb $DISPLAY &
          mvn -B test -Dtest=!Docker*,!Remote*,!*Manual*,!*Proxy*,!Edge*
    - name: Install browsers in Mac
      if: matrix.os == 'macos-latest'
      run: |
        brew install --cask firefox
        /Applications/Firefox.app/Contents/MacOS/firefox --version
        brew install --cask microsoft-edge
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge" -version
    - name: Run tests on macOS
      if: matrix.os == 'macos-latest'
      uses: nick-invision/retry@v3.0.2
      with:
        timeout_minutes: 30
        max_attempts: 1
        command: |
          mvn -B test -Dtest=!Remote*,!Docker*,!*Manual*,!*Proxy*
    - name: Run tests on Windows
      if: matrix.os == 'windows-latest'
      uses: nick-invision/retry@v3.0.2
      with:
        timeout_minutes: 30
        max_attempts: 1
        command: |
          mvn -B test -Dtest=!Remote*,!Docker*,!*Manual*,!*Proxy*
        shell: cmd
