name: docker-connect-host

on:
  workflow_dispatch:

jobs:
  docker-connect-host:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Start container (using host network)
      run: |
        docker run -d --cap-add=SYS_ADMIN --network=host selenoid/vnc:chrome_118.0
    - name: Wait for container
      run: |
        ./scripts/wait-for-it.sh --timeout=60 localhost:4444
    - name: Run Selenium test
      run: |
        mvn -B test -Dtest=RemoteChromeCdpTest
